### ISSUE TITLE
Let user cancel a mistake

### ISSUE THREAD

**Issue by gpicc** [Midblyte/tmnetbot#4]
If you send a message to the bot to be forwarded into the Best Of channel, you have no way to cancel the operation after send. A command should be introduced to revert the action in a short period of time (e.g. 2m) so that the rest of the schedule is untouched.

**Comment by Midblyte** [comment]
You can cancel the scheduling at any time from /info.

But you can't do anything once the message has been forwarded in the "Best Of" channel.
Handling this case case involves additional levels of complexity.

Do you think the current behaviour is fine?

**Comment by gpicc** [comment]
Oh my bad, I didn't see the option. Thanks - it's good for now.
